name: Cross Compile Go Project

on:
  pull_request:
    types: [opened, synchronize]
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            goarch: amd64
          - os: linux
            goarch: 386
          - os: linux
            goarch: arm
          - os: linux
            goarch: arm64
          - os: darwin
            goarch: amd64
          - os: darwin
            goarch: arm64
          - os: windows
            goarch: amd64
          - os: windows
            goarch: 386

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.1' # Set to specific Go version.

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libc6-dev libsqlite3-dev

    - name: Create output directory
      run: mkdir -p output

    - name: Compile Go for target
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        if [ "$GOOS" = "windows" ]; then
          go build -o output/gensokyo-hunyuan-${{ matrix.os }}-${{ matrix.goarch }}.exe
        else
          go build -o output/gensokyo-hunyuan-${{ matrix.os }}-${{ matrix.goarch }}
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gensokyo-hunyuan-${{ matrix.os }}-${{ matrix.goarch }}
        path: output/gensokyo-hunyuan-${{ matrix.os }}-${{ matrix.goarch }}${{ endsWith(matrix.os, 'windows') && '.exe' || '' }}

  prepare_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false

      - name: Upload Release Assets
        run: |
          for dir in output/*; do
            if [ -d "$dir" ]; then
              for file in "$dir"/*; do
                if [ -f "$file" ]; then
                  asset_name=$(basename "$file")
                  echo "Uploading ${asset_name}"
                  GITHUB_UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}
                  GITHUB_UPLOAD_URL="${GITHUB_UPLOAD_URL%\{*}"
                  GITHUB_UPLOAD_URL="${GITHUB_UPLOAD_URL%\?*}"
                  curl \
                  -X POST \
                  -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Content-Type: application/octet-stream" \
                  --data-binary @"${file}" \
                  "${GITHUB_UPLOAD_URL}?name=${asset_name}&label=${asset_name}"
                else
                  echo "Expected a file in ${dir}, but found something else."
                fi
              done
            else
              echo "Expected ${dir} to be a directory."
            fi
          done